# ------------------------------------------------------------------------------
# Configuration unique to this application.  Will be loaded as the `config`
# variable of the Application class.
# ------------------------------------------------------------------------------

config: {}
